//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOOPrintedFamily.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.CompositionOrder = new HashSet<CompositionOrder>();
        }
    
        public string ProductArticul { get; set; }
        public int NameId { get; set; }
        public string ProductDiscription { get; set; }
        public int PolId { get; set; }
        public int ProviderId { get; set; }
        public int CompositionId { get; set; }
        public byte ProductDiscount { get; set; }
        public decimal ProductCost { get; set; }
        public byte[] ProductImage { get; set; }
        public int ProductCountInStoke { get; set; }
    
        public virtual Composition Composition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompositionOrder> CompositionOrder { get; set; }
        public virtual Name Name { get; set; }
        public virtual Pol Pol { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
